Metrics/LineLength:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/lib/snowplow_ruby_duid/cookie_spec.rb'

Style/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/DateTime:
  Exclude:
    - 'lib/snowplow_ruby_duid/cookie.rb'
